version: '3'
services:
  nifi:
    ports:
      - 8443:8443/tcp
    environment:
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      NIFI_WEB_HTTP_PORT: 8443
    image: apache/nifi:latest
    links:
      - elasticsearch
  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    image: elasticsearch:6.8.2
  kibana:
    ports:
      - "5601:5601"
    image: kibana:6.8.2
    links:
      - elasticsearch
